### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by AmanOswal** [thuml/CDAN#24]
Please help to diagnose the error.
I have cuda installed, which I checked by 
print(torch.version.cuda)
10.2
print(torch.cuda.device_count())
1
print(torch.cuda.is_available())
True

Full Error:

THCudaCheck FAIL file=..\aten\src\THC\THCGeneral.cpp line=47 error=100 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "train_image.py", line 277, in <module>
    train(config)
  File "train_image.py", line 110, in train
    base_network = base_network.cuda()
  File "C:\Users\aman\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 307, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\aman\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 203, in _apply
    module._apply(fn)
  File "C:\Users\aman\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 225, in _apply
    param_applied = fn(param)
  File "C:\Users\aman\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 307, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\aman\anaconda3\lib\site-packages\torch\cuda\__init__.py", line 153, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (100) : no CUDA-capable device is detected at ..\aten\src\THC\THCGeneral.cpp:47

**Comment by AmanOswal** [comment]
If I remove all cuda() from code, then I get NotImplementedError. Please help.
